# Generated by Django 5.2.8 on 2026-07-16 20:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requerimentos', '0005_alter_uploadtemporario_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('prazo_correcao_dias', models.PositiveSmallIntegerField(choices=[(10, '10 dias'), (30, '30 dias'), (90, '90 dias')], default=30, verbose_name='prazo para correção')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'configuração da triagem',
                'verbose_name_plural': 'configurações da triagem',
            },
        ),
        migrations.CreateModel(
            name='ItemChecklistTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('confere_comprovantes', models.BooleanField(default=False, help_text='Indica que o item exige conferência dos documentos anexados ao requerimento.')),
                ('ativo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'item do checklist de triagem',
                'verbose_name_plural': 'itens do checklist de triagem',
                'ordering': ['ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='TriagemRequerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rodada', models.PositiveSmallIntegerField(default=1)),
                ('resultado', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('APTO', 'Apto para análise'), ('PENDENCIA', 'Pendente de correção')], default='EM_ANDAMENTO', max_length=20)),
                ('iniciada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('orientacao_correcao', models.TextField(blank=True)),
                ('prazo_correcao_dias_snapshot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prazo_correcao_ate', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('requerimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triagens', to='requerimentos.requerimento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triagens_rsc_responsavel', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'triagem de requerimento',
                'verbose_name_plural': 'triagens de requerimentos',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='VerificacaoChecklistTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_codigo_snapshot', models.CharField(max_length=30)),
                ('item_titulo_snapshot', models.CharField(max_length=255)),
                ('item_descricao_snapshot', models.TextField(blank=True)),
                ('item_obrigatorio_snapshot', models.BooleanField(default=True)),
                ('item_confere_comprovantes_snapshot', models.BooleanField(default=False)),
                ('situacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFORME', 'Conforme'), ('NAO_CONFORME', 'Não conforme'), ('NAO_APLICAVEL', 'Não aplicável')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificacoes', to='triagem.itemchecklisttriagem')),
                ('triagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes', to='triagem.triagemrequerimento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'verificação do checklist',
                'verbose_name_plural': 'verificações do checklist',
                'ordering': ['item__ordem', 'item__codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='triagemrequerimento',
            constraint=models.UniqueConstraint(fields=('requerimento', 'rodada'), name='uniq_triagem_requerimento_rodada'),
        ),
        migrations.AddConstraint(
            model_name='triagemrequerimento',
            constraint=models.CheckConstraint(condition=models.Q(('rodada__gt', 0)), name='ck_triagem_rodada_positiva'),
        ),
        migrations.AddConstraint(
            model_name='verificacaochecklisttriagem',
            constraint=models.UniqueConstraint(fields=('triagem', 'item'), name='uniq_verificacao_triagem_item'),
        ),
    ]
