# Generated by Django 5.2.8 on 2026-07-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triagemrequerimento',
            options={'ordering': ['-iniciada_em'], 'permissions': [('acessar_fila_triagem', 'Pode acessar a fila de triagem'), ('iniciar_triagem', 'Pode iniciar triagem de requerimento'), ('alterar_triagem', 'Pode alterar triagem de requerimento'), ('concluir_triagem', 'Pode concluir triagem de requerimento')], 'verbose_name': 'triagem de requerimento', 'verbose_name_plural': 'triagens de requerimentos'},
        ),
    ]
