# Generated by Django 5.2.8 on 2026-07-16 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comissoes', '0001_initial'),
        ('pessoas', '0001_initial'),
        ('pontuacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade_declarada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pontuacao_declarada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacao', models.TextField(blank=True)),
                ('item_codigo_snapshot', models.CharField(max_length=20)),
                ('item_descricao_snapshot', models.TextField()),
                ('item_unidade_snapshot', models.CharField(max_length=100)),
                ('item_pontos_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_limite_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_exige_anexo_snapshot', models.BooleanField(default=True)),
                ('quantidade_validada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pontuacao_validada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('situacao_validacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VALIDADO', 'Validado'), ('AJUSTADO', 'Ajustado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20)),
                ('justificativa_validacao', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='pontuacao.itempontuacao')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'lançamento de item',
                'verbose_name_plural': 'lançamentos de itens',
                'ordering': ['item__requisito__ordem', 'item__ordem'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arquivo', models.FileField(upload_to='requerimentos/%Y/%m/%d/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=150)),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ativo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='requerimentos.lancamentoitem')),
            ],
            options={
                'verbose_name': 'documento do item',
                'verbose_name_plural': 'documentos dos itens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('situacao', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Submetido'), ('EM_TRIAGEM', 'Em triagem'), ('PENDENTE_CORRECAO', 'Pendente de correção'), ('EM_ANALISE', 'Em análise'), ('EM_DILIGENCIA', 'Em diligência'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=30)),
                ('pontuacao_declarada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pontuacao_validada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('submetido_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao_geral', models.TextField(blank=True)),
                ('comissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimentos', to='comissoes.comissao')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('nivel_pretendido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimentos', to='pontuacao.nivelrsc')),
                ('requerente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimentos_rsc', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimentos_rsc', to='pessoas.vinculofuncional')),
            ],
            options={
                'verbose_name': 'requerimento',
                'verbose_name_plural': 'requerimentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lancamentoitem',
            name='requerimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='requerimentos.requerimento'),
        ),
        migrations.CreateModel(
            name='HistoricoRequerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('situacao_anterior', models.CharField(blank=True, max_length=30)),
                ('situacao_nova', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('requerimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='requerimentos.requerimento')),
            ],
            options={
                'verbose_name': 'histórico do requerimento',
                'verbose_name_plural': 'históricos dos requerimentos',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='requerimento',
            index=models.Index(fields=['requerente', 'situacao'], name='idx_req_usuario_situacao'),
        ),
        migrations.AddIndex(
            model_name='requerimento',
            index=models.Index(fields=['vinculo', 'situacao'], name='idx_req_vinculo_situacao'),
        ),
        migrations.AddIndex(
            model_name='requerimento',
            index=models.Index(fields=['situacao', 'submetido_em'], name='idx_req_situacao_submissao'),
        ),
        migrations.AddConstraint(
            model_name='lancamentoitem',
            constraint=models.UniqueConstraint(fields=('requerimento', 'item'), name='uniq_lancamento_requerimento_item'),
        ),
        migrations.AddConstraint(
            model_name='lancamentoitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_declarada__gt', 0)), name='ck_lancamento_quantidade_positiva'),
        ),
    ]
