# Generated by Django 5.2.8 on 2026-07-16 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(blank=True, max_length=30)),
                ('ato_designacao', models.CharField(blank=True, max_length=150)),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'comissão',
                'verbose_name_plural': 'comissões',
                'ordering': ['-ativa', '-inicio_vigencia', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MembroComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_snapshot', models.CharField(max_length=255)),
                ('email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('papel', models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('VICE_PRESIDENTE', 'Vice-presidente'), ('MEMBRO', 'Membro'), ('SECRETARIA', 'Secretaria')], default='MEMBRO', max_length=30)),
                ('inicio_mandato', models.DateField()),
                ('fim_mandato', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='comissoes.comissao')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participacoes_comissoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membro da comissão',
                'verbose_name_plural': 'membros da comissão',
                'ordering': ['comissao', 'papel', 'nome_snapshot'],
            },
        ),
        migrations.AddConstraint(
            model_name='comissao',
            constraint=models.CheckConstraint(condition=models.Q(('fim_vigencia__isnull', True), ('fim_vigencia__gte', models.F('inicio_vigencia')), _connector='OR'), name='ck_comissao_vigencia_valida'),
        ),
        migrations.AddConstraint(
            model_name='membrocomissao',
            constraint=models.CheckConstraint(condition=models.Q(('fim_mandato__isnull', True), ('fim_mandato__gte', models.F('inicio_mandato')), _connector='OR'), name='ck_membro_mandato_valido'),
        ),
    ]
