"""Dados iniciais de requisitos e itens do RSC-PCCTAE.

A interface usa apenas item + quantidade; períodos e demais detalhes são comprovados nos anexos.
"""

FUNDAMENTO_LEGAL = "Decreto nº 13.048/2026"
FONTE = "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2026/decreto/d13048.htm"

REQUISITOS = [{'codigo': 'I',
  'ordem': 1,
  'nome': 'Participação em grupos de trabalho, comissões, comitês, núcleos, representações ou similares',
  'descricao': 'Participação formalmente instituída ou reconhecida pelo órgão ou pela entidade.'},
 {'codigo': 'II',
  'ordem': 2,
  'nome': 'Participação e atuação em projetos institucionais, gestão e apoio às atividades finalísticas',
  'descricao': 'Projetos institucionais na gestão, no apoio ao ensino, à pesquisa, à extensão, de inovação e '
               'assistência especializada.'},
 {'codigo': 'III',
  'ordem': 3,
  'nome': 'Recebimento de premiação em evento de reconhecimento público',
  'descricao': 'Premiações por projetos implementados na administração pública.'},
 {'codigo': 'IV',
  'ordem': 4,
  'nome': 'Designação para assunção de responsabilidades técnico-administrativas ou especializadas',
  'descricao': 'Responsabilidades técnicas, administrativas ou especializadas.'},
 {'codigo': 'V',
  'ordem': 5,
  'nome': 'Exercício de função, cargo de direção ou assessoramento institucional',
  'descricao': 'Exercício como titular ou substituto formalmente designado.'},
 {'codigo': 'VI',
  'ordem': 6,
  'nome': 'Produção, prospecção e difusão de conhecimento científico ou técnico',
  'descricao': 'Produções, inovação, formação, pesquisa e difusão do conhecimento.'}]

NIVEIS = [{'codigo': 'I',
  'nome': 'RSC-PCCTAE I',
  'ordem': 1,
  'pontuacao_minima': '10.00',
  'quantidade_minima_itens': 1,
  'descricao': 'Servidor que não concluiu o ensino fundamental',
  'requisitos_obrigatorios': []},
 {'codigo': 'II',
  'nome': 'RSC-PCCTAE II',
  'ordem': 2,
  'pontuacao_minima': '15.00',
  'quantidade_minima_itens': 2,
  'descricao': 'Conclusão do ensino fundamental',
  'requisitos_obrigatorios': []},
 {'codigo': 'III',
  'nome': 'RSC-PCCTAE III',
  'ordem': 3,
  'pontuacao_minima': '25.00',
  'quantidade_minima_itens': 2,
  'descricao': 'Conclusão do ensino médio ou técnico de nível médio',
  'requisitos_obrigatorios': []},
 {'codigo': 'IV',
  'nome': 'RSC-PCCTAE IV',
  'ordem': 4,
  'pontuacao_minima': '30.00',
  'quantidade_minima_itens': 3,
  'descricao': 'Graduação no ensino superior',
  'requisitos_obrigatorios': ['II', 'IV', 'V', 'VI']},
 {'codigo': 'V',
  'nome': 'RSC-PCCTAE V',
  'ordem': 5,
  'pontuacao_minima': '52.00',
  'quantidade_minima_itens': 5,
  'descricao': 'Pós-graduação lato sensu',
  'requisitos_obrigatorios': ['IV', 'V', 'VI']},
 {'codigo': 'VI',
  'nome': 'RSC-PCCTAE VI',
  'ordem': 6,
  'pontuacao_minima': '75.00',
  'quantidade_minima_itens': 7,
  'descricao': 'Mestrado',
  'requisitos_obrigatorios': ['VI']}]

ITENS = [{'codigo': 'I.1',
  'requisito': 'I',
  'ordem': 10,
  'descricao': 'Exercício do mandato como membro de conselhos superiores e conselhos de unidades e órgãos colegiados '
               'da Instituição Federal de Ensino',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '3'},
 {'codigo': 'I.2',
  'requisito': 'I',
  'ordem': 20,
  'descricao': 'Coordenação ou presidência de núcleos, representações, grupos de trabalho ou similares, comissões ou '
               'comitês previstos no âmbito da administração pública, regularmente instituídos ou reconhecidos pelo '
               'órgão ou pela entidade',
  'unidade': 'Por designação',
  'pontos': '4.5'},
 {'codigo': 'I.3',
  'requisito': 'I',
  'ordem': 30,
  'descricao': 'Participação como membro de núcleos, representações, grupos de trabalho ou similares, comissões ou '
               'comitês previstos no âmbito da administração pública, regularmente instituídos',
  'unidade': 'Por designação',
  'pontos': '3'},
 {'codigo': 'I.4',
  'requisito': 'I',
  'ordem': 40,
  'descricao': 'Participação como defensor dativo ou como membro de equipe designada em processos de apuração de '
               'materialidade e responsabilidade, como sindicância, processo administrativo disciplinar e tomada de '
               'contas especial',
  'unidade': 'Por designação',
  'pontos': '3'},
 {'codigo': 'I.5',
  'requisito': 'I',
  'ordem': 50,
  'descricao': 'Atuação em atividades de organização, fiscalização ou execução de exame de seleção, vestibular ou '
               'concursos',
  'unidade': 'Por designação',
  'pontos': '4.5'},
 {'codigo': 'I.6',
  'requisito': 'I',
  'ordem': 60,
  'descricao': 'Atuação em atividades de elaboração, revisão e/ou correção de provas de exame de seleção, vestibular '
               'ou concursos',
  'unidade': 'Por designação',
  'pontos': '3'},
 {'codigo': 'I.7',
  'requisito': 'I',
  'ordem': 70,
  'descricao': 'Exercício de mandato em entidade sindical da categoria',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '1.5'},
 {'codigo': 'I.8',
  'requisito': 'I',
  'ordem': 80,
  'descricao': 'Participação como membro em programas ou projetos de políticas públicas externas à Instituição Federal '
               'de Ensino, desde que comprovada a obtenção de resultados institucionais relevantes',
  'unidade': 'Por designação',
  'pontos': '3'},
 {'codigo': 'I.9',
  'requisito': 'I',
  'ordem': 90,
  'descricao': 'Representação legal da Instituição Federal de Ensino junto a órgãos e entidades do Poder Público ou '
               'responsabilidade técnica junto a órgãos de fiscalização, controle e regulação',
  'unidade': 'Por designação',
  'pontos': '7.5'},
 {'codigo': 'I.10',
  'requisito': 'I',
  'ordem': 100,
  'descricao': 'Atuação técnica externa, formalmente autorizada ou reconhecida pela Instituição Federal de Ensino de '
               'lotação, em órgãos estatais ou paraestatais, escolas de governo, agências reguladoras ou organismos '
               'internacionais, com contribuição ou repercussão institucional',
  'unidade': 'Por produto',
  'pontos': '4.5'},
 {'codigo': 'II.1',
  'requisito': 'II',
  'ordem': 10,
  'descricao': 'Coordenação de projetos institucionais de ensino, pesquisa, extensão, gestão e inovação',
  'unidade': 'Por projeto',
  'pontos': '7.5'},
 {'codigo': 'II.2',
  'requisito': 'II',
  'ordem': 20,
  'descricao': 'Participação em atividades técnicas e/ou especializadas em projetos, incluída a elaboração de projetos '
               'pedagógicos, programas e/ou ações institucionais de ensino, pesquisa, extensão, gestão e inovação',
  'unidade': 'Por projeto',
  'pontos': '4.5'},
 {'codigo': 'II.3',
  'requisito': 'II',
  'ordem': 30,
  'descricao': 'Participação em comissão ou conselho editorial de livros, revistas ou publicações científicas ou '
               'outras publicações acadêmicas',
  'unidade': 'Por mandato',
  'pontos': '7.5'},
 {'codigo': 'II.4',
  'requisito': 'II',
  'ordem': 40,
  'descricao': 'Participação em atividade de cooperação técnica interinstitucional em projetos institucionais',
  'unidade': 'Por projeto',
  'pontos': '3'},
 {'codigo': 'II.5',
  'requisito': 'II',
  'ordem': 50,
  'descricao': 'Participação em atividades de orientação, tutoria, preceptoria ou supervisão',
  'unidade': 'Por designação',
  'pontos': '3'},
 {'codigo': 'II.6',
  'requisito': 'II',
  'ordem': 60,
  'descricao': 'Participação em atividades de produção ou reformulação de material acessível ou técnico de referência, '
               'como manuais e roteiros técnicos',
  'unidade': 'Por produto',
  'pontos': '3'},
 {'codigo': 'II.7',
  'requisito': 'II',
  'ordem': 70,
  'descricao': 'Participação em atividade de avaliação de trabalho ou atuação como jurado em eventos acadêmicos, '
               'científicos, culturais, esportivos e técnicos',
  'unidade': 'Por evento',
  'pontos': '3'},
 {'codigo': 'II.8',
  'requisito': 'II',
  'ordem': 80,
  'descricao': 'Participação em atividade institucional de produção audiovisual, artística, exposição, podcast ou '
               'outras formas de apresentação',
  'unidade': 'Por projeto',
  'pontos': '3'},
 {'codigo': 'II.9',
  'requisito': 'II',
  'ordem': 90,
  'descricao': 'Participação em programas de formação continuada e/ou ações de desenvolvimento de competências, desde '
               'que não utilizada para fins de aceleração da promoção na carreira, com carga horária mínima de dez '
               'horas',
  'unidade': 'Por capacitação',
  'pontos': '1'},
 {'codigo': 'II.10',
  'requisito': 'II',
  'ordem': 100,
  'descricao': 'Desempenho de atividade técnica especializada, formalmente reconhecida pela Instituição Federal de '
               'Ensino, com demonstração de domínio técnico diferenciado e contribuição institucional relevante na '
               'área de atuação',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '1'},
 {'codigo': 'II.11',
  'requisito': 'II',
  'ordem': 110,
  'descricao': 'Participação em capacitação, fórum, oficina, workshop e congresso, com carga horária mínima de dez '
               'horas, vinculada aos interesses da Instituição Federal de Ensino',
  'unidade': 'Por evento',
  'pontos': '1'},
 {'codigo': 'III.1',
  'requisito': 'III',
  'ordem': 10,
  'descricao': 'Recebimento de premiação de âmbito internacional por projeto implementado na administração pública',
  'unidade': 'Por prêmio',
  'pontos': '20'},
 {'codigo': 'III.2',
  'requisito': 'III',
  'ordem': 20,
  'descricao': 'Recebimento de premiação de âmbito nacional por projeto implementado na administração pública',
  'unidade': 'Por prêmio',
  'pontos': '15'},
 {'codigo': 'III.3',
  'requisito': 'III',
  'ordem': 30,
  'descricao': 'Recebimento de premiação de âmbito local ou institucional, formalmente instituído, por projeto '
               'implementado na administração pública',
  'unidade': 'Por prêmio',
  'pontos': '7.5'},
 {'codigo': 'IV.1',
  'requisito': 'IV',
  'ordem': 10,
  'descricao': 'Atuação tecnicamente qualificada na operação, implantação, suporte ou apoio ao desenvolvimento, '
               'parametrização ou aperfeiçoamento de sistemas estruturantes da administração pública',
  'unidade': 'Por sistema',
  'pontos': '4.5'},
 {'codigo': 'IV.2',
  'requisito': 'IV',
  'ordem': 20,
  'descricao': 'Elaboração de projeto básico ou de termo de referência, ou participação como membro de equipe de '
               'planejamento de contratação',
  'unidade': 'Por designação',
  'pontos': '3'},
 {'codigo': 'IV.3',
  'requisito': 'IV',
  'ordem': 30,
  'descricao': 'Exercício de atividades de gestão ou fiscalização de contratos de aquisição, serviços, convênios, '
               'acordos ou instrumentos correlatos',
  'unidade': 'Por designação',
  'pontos': '4.5'},
 {'codigo': 'IV.4',
  'requisito': 'IV',
  'ordem': 40,
  'descricao': 'Exercício de atividades relacionadas à licitação e às suas excepcionalidades',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '3'},
 {'codigo': 'IV.5',
  'requisito': 'IV',
  'ordem': 50,
  'descricao': 'Participação em atividades de apoio técnico especializado em políticas, programas e ações de promoção '
               'na área de saúde humana, animal e ambiente, de acessibilidade ou diversidade, de interesse '
               'institucional',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '3'},
 {'codigo': 'IV.6',
  'requisito': 'IV',
  'ordem': 60,
  'descricao': 'Atuação tecnicamente qualificada em ambientes ou processos que demandem condições especiais de '
               'segurança, cuidado ou conformidade com requisitos legais e regulatórios, desde que não receba '
               'adicional de periculosidade ou insalubridade em razão das mesmas condições',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '3'},
 {'codigo': 'IV.7',
  'requisito': 'IV',
  'ordem': 70,
  'descricao': 'Atuação em sistemas e/ou processos de trabalho institucionais em ensino, pesquisa, extensão, gestão e '
               'inovação, desde que não constitua atividade habitual do cargo',
  'unidade': 'Por designação',
  'pontos': '3'},
 {'codigo': 'IV.8',
  'requisito': 'IV',
  'ordem': 80,
  'descricao': 'Atuação como responsável por setor ou por unidade, formalmente designado, desde que a designação não '
               'gere pagamento de remuneração',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '4.5'},
 {'codigo': 'V.1-T',
  'requisito': 'V',
  'ordem': 11,
  'descricao': 'Exercício de cargo de direção CD-02 ou equivalente — titular',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '9'},
 {'codigo': 'V.1-S',
  'requisito': 'V',
  'ordem': 12,
  'descricao': 'Exercício de cargo de direção CD-02 ou equivalente — substituto',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '4.5'},
 {'codigo': 'V.2-T',
  'requisito': 'V',
  'ordem': 21,
  'descricao': 'Exercício de cargo de direção CD-03 e CD-04 ou equivalente — titular',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '7.5'},
 {'codigo': 'V.2-S',
  'requisito': 'V',
  'ordem': 22,
  'descricao': 'Exercício de cargo de direção CD-03 e CD-04 ou equivalente — substituto',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '3'},
 {'codigo': 'V.3-T',
  'requisito': 'V',
  'ordem': 31,
  'descricao': 'Exercício de função gratificada FG-01 e FG-02 ou equivalente — titular',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '4.5'},
 {'codigo': 'V.3-S',
  'requisito': 'V',
  'ordem': 32,
  'descricao': 'Exercício de função gratificada FG-01 e FG-02 ou equivalente — substituto',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '1.5'},
 {'codigo': 'V.4-T',
  'requisito': 'V',
  'ordem': 41,
  'descricao': 'Exercício de função gratificada a partir da FG-03 ou equivalente — titular',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '3'},
 {'codigo': 'V.4-S',
  'requisito': 'V',
  'ordem': 42,
  'descricao': 'Exercício de função gratificada a partir da FG-03 ou equivalente — substituto',
  'unidade': 'Por ano ou fração acima de seis meses',
  'pontos': '1'},
 {'codigo': 'VI.1',
  'requisito': 'VI',
  'ordem': 10,
  'descricao': 'Carta patente relacionada aos interesses institucionais',
  'unidade': 'Por patente',
  'pontos': '30'},
 {'codigo': 'VI.2',
  'requisito': 'VI',
  'ordem': 20,
  'descricao': 'Participação relevante no desenvolvimento de protótipos, depósitos e/ou registros de propriedade '
               'intelectual ou privilégio de invenção relacionada aos interesses institucionais',
  'unidade': 'Por projeto',
  'pontos': '25'},
 {'codigo': 'VI.3',
  'requisito': 'VI',
  'ordem': 30,
  'descricao': 'Participação em transferência de tecnologia, licenciamento ou exploração de ativo tecnológico, como '
               'autor ou inventor, relacionada aos interesses institucionais',
  'unidade': 'Por produto',
  'pontos': '20'},
 {'codigo': 'VI.4',
  'requisito': 'VI',
  'ordem': 40,
  'descricao': 'Conclusão de curso de educação formal superior ao exigido para o ingresso no cargo de que é titular e '
               'que não seja utilizado para percepção de Incentivo à Qualificação',
  'unidade': 'Por curso',
  'pontos': '15'},
 {'codigo': 'VI.5',
  'requisito': 'VI',
  'ordem': 50,
  'descricao': 'Participação relevante na implantação ou desenvolvimento de produto, projeto, processo, técnica ou '
               'tecnologia de interesse institucional',
  'unidade': 'Por produto',
  'pontos': '15'},
 {'codigo': 'VI.6',
  'requisito': 'VI',
  'ordem': 60,
  'descricao': 'Atuação em atividade de liderança ou vice-liderança de grupo de pesquisa ou extensão registrado em '
               'órgão ou sistema oficial de reconhecimento institucional',
  'unidade': 'Por grupo de pesquisa',
  'pontos': '7.5'},
 {'codigo': 'VI.7',
  'requisito': 'VI',
  'ordem': 70,
  'descricao': 'Participação como membro em grupo de pesquisa devidamente registrado em órgão ou sistema oficial de '
               'reconhecimento institucional',
  'unidade': 'Por projeto',
  'pontos': '3'},
 {'codigo': 'VI.8',
  'requisito': 'VI',
  'ordem': 80,
  'descricao': 'Aprovação de projeto para a captação de recursos para a Instituição Federal de Ensino',
  'unidade': 'Por projeto',
  'pontos': '7.5'},
 {'codigo': 'VI.9',
  'requisito': 'VI',
  'ordem': 90,
  'descricao': 'Publicação ou organização de livro relacionado aos interesses institucionais, com ISBN e Conselho '
               'Editorial',
  'unidade': 'Por produto',
  'pontos': '20'},
 {'codigo': 'VI.10',
  'requisito': 'VI',
  'ordem': 100,
  'descricao': 'Autoria ou coautoria de capítulo de livro, artigo publicado em revista especializada, jornal '
               'científico ou periódico, relacionado aos interesses institucionais',
  'unidade': 'Por publicação',
  'pontos': '7.5'},
 {'codigo': 'VI.11',
  'requisito': 'VI',
  'ordem': 110,
  'descricao': 'Apresentação de trabalho de interesse institucional em congresso, seminário ou outros eventos',
  'unidade': 'Por produto',
  'pontos': '4.5'},
 {'codigo': 'VI.12',
  'requisito': 'VI',
  'ordem': 120,
  'descricao': 'Produção de material técnico, científico, metodológico ou administrativo estruturado que vise à '
               'difusão do conhecimento',
  'unidade': 'Por produto',
  'pontos': '4.5'},
 {'codigo': 'VI.13',
  'requisito': 'VI',
  'ordem': 130,
  'descricao': 'Avaliação de projeto de ensino, pesquisa, extensão e/ou inovação',
  'unidade': 'Por projeto',
  'pontos': '4.5'},
 {'codigo': 'VI.14',
  'requisito': 'VI',
  'ordem': 140,
  'descricao': 'Participação em atividade de difusão ou apoio à formação institucional como expositor, facilitador ou '
               'colaborador',
  'unidade': 'Por evento',
  'pontos': '3'},
 {'codigo': 'VI.15',
  'requisito': 'VI',
  'ordem': 150,
  'descricao': 'Atuação formalmente autorizada como instrutor, tutor, palestrante, autor de conteúdo técnico ou '
               'orientador em ação formativa estruturada de interesse institucional, prevista em plano ou programa de '
               'desenvolvimento de pessoas',
  'unidade': 'Por curso',
  'pontos': '4.5'},
 {'codigo': 'VI.16',
  'requisito': 'VI',
  'ordem': 160,
  'descricao': 'Atuação na coordenação de congresso, simpósio ou seminário de interesse institucional',
  'unidade': 'Por evento',
  'pontos': '3.5'},
 {'codigo': 'VI.17',
  'requisito': 'VI',
  'ordem': 170,
  'descricao': 'Exercício de atividade de coorientação de trabalho de conclusão de curso em diferentes modalidades de '
               'ensino',
  'unidade': 'Por evento',
  'pontos': '4.5'}]
