# Generated by Django 5.2.8 on 2026-07-16 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelRSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('pontuacao_minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_minima_itens', models.PositiveSmallIntegerField(default=1)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'nível de RSC',
                'verbose_name_plural': 'níveis de RSC',
                'ordering': ['ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='NivelRequisitoObrigatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontuacao.nivelrsc')),
            ],
            options={
                'verbose_name': 'requisito obrigatório do nível',
                'verbose_name_plural': 'requisitos obrigatórios dos níveis',
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'requisito',
                'verbose_name_plural': 'requisitos',
                'ordering': ['ordem', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='nivelrsc',
            name='requisitos_obrigatorios',
            field=models.ManyToManyField(blank=True, related_name='niveis_obrigatorios', through='pontuacao.NivelRequisitoObrigatorio', to='pontuacao.requisito'),
        ),
        migrations.AddField(
            model_name='nivelrequisitoobrigatorio',
            name='requisito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pontuacao.requisito'),
        ),
        migrations.CreateModel(
            name='ItemPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(max_length=100)),
                ('pontos_por_quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_pontos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_quantidade', models.CharField(choices=[('INTEIRA', 'Número inteiro'), ('DECIMAL', 'Número decimal')], default='INTEIRA', max_length=10)),
                ('exige_anexo', models.BooleanField(default=True)),
                ('observacao_permitida', models.BooleanField(default=True)),
                ('orientacao', models.TextField(blank=True)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='pontuacao.requisito')),
            ],
            options={
                'verbose_name': 'item de pontuação',
                'verbose_name_plural': 'itens de pontuação',
                'ordering': ['requisito__ordem', 'ordem', 'codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='requisito',
            index=models.Index(fields=['ativo', 'ordem'], name='idx_req_ativo_ordem'),
        ),
        migrations.AddConstraint(
            model_name='nivelrsc',
            constraint=models.CheckConstraint(condition=models.Q(('pontuacao_minima__gte', 0)), name='ck_nivel_pontos_nao_negativos'),
        ),
        migrations.AddConstraint(
            model_name='nivelrequisitoobrigatorio',
            constraint=models.UniqueConstraint(fields=('nivel', 'requisito'), name='uniq_nivel_requisito_obrigatorio'),
        ),
        migrations.AddIndex(
            model_name='itempontuacao',
            index=models.Index(fields=['requisito', 'ativo'], name='idx_item_req_ativo'),
        ),
        migrations.AddConstraint(
            model_name='itempontuacao',
            constraint=models.CheckConstraint(condition=models.Q(('pontos_por_quantidade__gte', 0)), name='ck_item_pontos_nao_negativos'),
        ),
        migrations.AddConstraint(
            model_name='itempontuacao',
            constraint=models.CheckConstraint(condition=models.Q(('limite_pontos__isnull', True), ('limite_pontos__gte', 0), _connector='OR'), name='ck_item_limite_nao_negativo'),
        ),
    ]
