# Generated by Django 5.2.8 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0004_alter_eventoauditoria_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventoauditoria",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCESSO", "Login realizado"),
                    ("LOGIN_FALHA", "Falha de login"),
                    ("LOGOUT", "Logout realizado"),
                    ("ACESSO_NEGADO", "Acesso negado"),
                    ("REQUERIMENTO_VISUALIZADO", "Requerimento visualizado"),
                    ("DADOS_FUNCIONAIS_VISUALIZADOS", "Dados funcionais visualizados"),
                    ("IMPORTACAO_USUARIO_SIG", "Importação de usuário do SIG"),
                    ("CADASTRO_CRIADO", "Cadastro criado"),
                    ("CADASTRO_ALTERADO", "Cadastro alterado"),
                    ("CADASTRO_EXCLUIDO", "Cadastro excluído"),
                    ("REQUERIMENTO_CRIADO", "Requerimento criado"),
                    ("ITEM_REQUERIMENTO_SALVO", "Item do requerimento salvo"),
                    ("ITEM_REQUERIMENTO_REMOVIDO", "Item do requerimento removido"),
                    ("REQUERIMENTO_SUBMETIDO", "Requerimento submetido"),
                    ("UPLOAD_TEMPORARIO_CRIADO", "Upload temporário criado"),
                    ("UPLOAD_TEMPORARIO_REMOVIDO", "Upload temporário removido"),
                    ("DOCUMENTO_ADICIONADO", "Documento adicionado"),
                    ("DOCUMENTO_REMOVIDO", "Documento removido"),
                    ("DOCUMENTO_BAIXADO", "Documento baixado"),
                    ("FORMULARIO_F00_GERADO", "Formulário F-00 gerado"),
                    ("TRIAGEM_INICIADA", "Triagem iniciada"),
                    ("TRIAGEM_SALVA", "Triagem salva"),
                    ("TRIAGEM_CONCLUIDA", "Triagem concluída"),
                    ("IMPERSONACAO_INICIADA", "Simulação iniciada"),
                    ("IMPERSONACAO_ENCERRADA", "Simulação encerrada"),
                    ("ACAO_BLOQUEADA_IMPERSONACAO", "Ação bloqueada durante simulação"),
                ],
                db_index=True,
                max_length=60,
            ),
        ),
    ]
